const arrProduct = [
  {
    id: "001",
    sale: "Sustainable Materials",
    name: "Nike Court Vision Low Next Nature",
    image: [
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh1.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh2.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh3.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh4.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh5.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh5.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh6.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh7.png",
    ],
    information: "Women's Shoes",
    cout: "65.97",
    coutsale: "$115",
    hundredthsSale: "14%",
  },
  {
    id: "002",
    sale: "Sustainable Materials",
    name: "Nike Court Vision Low Next Nature",
    image: [
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh1.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh2.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh3.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh4.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh5.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh5.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh6.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh7.png",
    ],
    information: "Women's Shoes",
    cout: "65.97",
    coutsale: "$115",
    hundredthsSale: "14%",
  },
  {
    id: "003",
    sale: "Sustainable Materials",
    name: "Nike Court Vision Low Next Nature",
    image: [
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh1.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh2.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh3.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh4.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh5.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh5.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh6.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh7.png",
    ],
    information: "Women's Shoes",
    cout: "65.97",
    coutsale: "$115",
    hundredthsSale: "14%",
  },
  {
    id: "004",
    sale: "Sustainable Materials",
    name: "Nike Court Vision Low Next Nature",
    image: [
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh1.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh2.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh3.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh4.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh5.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh5.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh6.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh7.png",
    ],
    information: "Women's Shoes",
    cout: "65.97",
    coutsale: "$115",
    hundredthsSale: "14%",
  },
  {
    id: "005",
    sale: "Sustainable Materials",
    name: "Nike Court Vision Low Next Nature",
    image: [
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh1.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh2.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh3.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh4.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh5.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh5.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh6.png",
      "/đồ án 1/acseet/img/imgproduct/nikecount/anh7.png",
    ],
    information: "Women's Shoes",
    cout: "65.97",
    coutsale: "$115",
    hundredthsSale: "14%",
  },
];
